# Generated by Django 6.0.3 on 2026-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_skinprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprofile',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='skin_color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
