# Generated by Django 6.0.3 on 2026-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skinprofile_country_skinprofile_skin_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprofile',
            name='item_count',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='recommended_routine',
            field=models.JSONField(default=list),
        ),
    ]
